# Generated by Django 5.2.9 on 2026-05-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_address_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('STANDARD', 'Обычный'), ('EXPRESS', 'Срочный')], default='STANDARD', max_length=10),
        ),
    ]
